// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6qUFTlvGlyWTcqn4A2tBjpeAQm1I_b_s',
    appId: '1:933189481718:web:55f0f57bb7c4724ae328d7',
    messagingSenderId: '933189481718',
    projectId: 'codeui-node',
    authDomain: 'codeui-node.firebaseapp.com',
    storageBucket: 'codeui-node.appspot.com',
    measurementId: 'G-D3CCCJZTZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJTR1WEywLbVQ4nkO_HglmgGgFOJUkHhQ',
    appId: '1:933189481718:android:397be71696173ec2e328d7',
    messagingSenderId: '933189481718',
    projectId: 'codeui-node',
    storageBucket: 'codeui-node.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjfC6MoI9UHRBP4ku9beKtqA9GvNO2C7g',
    appId: '1:933189481718:ios:cb6c4f1a24200faae328d7',
    messagingSenderId: '933189481718',
    projectId: 'codeui-node',
    storageBucket: 'codeui-node.appspot.com',
    iosClientId: '933189481718-6je7bqtmsg6bhfpr56f29fbej6ojpv7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjfC6MoI9UHRBP4ku9beKtqA9GvNO2C7g',
    appId: '1:933189481718:ios:5a1927d970aecbd4e328d7',
    messagingSenderId: '933189481718',
    projectId: 'codeui-node',
    storageBucket: 'codeui-node.appspot.com',
    iosClientId: '933189481718-87euguofpnugj378tk0gh35ahhhilg5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile.RunnerTests',
  );
}
